<a href="https://colab.research.google.com/github/jostina/Week-1-2-Data-Cleaning-Exploratory-Data-Analysis/blob/main/Week_4_Supervised_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    mean_squared_error,
    accuracy_score,
    classification_report,
    confusion_matrix
)

#  PART 1: Regression - House Prices Dataset

In [2]:
# Load dataset
house_data = pd.read_csv("/content/Housing_Cleaned.csv")

In [3]:
# Display first five rows
house_data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [5]:
# Check for missing data
house_data.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [6]:
# Convert categorical columns to numbers
house_data = pd.get_dummies(house_data, drop_first=True)

In [7]:
# Select Features and Target
X = house_data.drop("price", axis=1)
y = house_data["price"]

In [8]:
# Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("\nTraining Samples:", len(X_train))
print("Testing Samples:", len(X_test))

Training Samples: 436
Testing Samples: 109

In [9]:
# Train Linear Regression Model
model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [10]:
# Make Predictions
predictions = model.predict(X_test)

In [11]:
# Evaluate Model
rmse = np.sqrt(mean_squared_error(y_test, predictions))

print("\nLinear Regression Results")
print("--------------------------")
print("RMSE:", round(rmse, 2))

Linear Regression Results
--------------------------
RMSE: 1324506.96